import { test, expect } from "@playwright/test";

test("una familia completa el ciclo de puntos, solicitudes y recompensas en escritorio y móvil", async ({ page, browser }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await page.getByLabel("Nombre de la familia").fill("Nuestra familia");
  await page.getByLabel("Nombre de acceso").fill("AdultoTest");
  await page.getByLabel("Contraseña del adulto").fill("ClaveAdulto2026!");
  await page.getByRole("button", { name: "Crear nuestro espacio" }).click();
  await expect(page.getByRole("heading", { name: "Hoy crecemos juntos" })).toBeVisible();
  await page.getByRole("button", { name: "Añadir mi primer hijo" }).click();
  for (const name of ["Alba", "Bruno"]) {
    const form = page.getByRole("form", { name: "Añadir hijo", exact: true });
    if (!(await form.isVisible())) await page.locator("summary").filter({ hasText: "Añadir un hijo" }).click();
    await form.getByLabel("Nombre de acceso").fill(name);
    await form.getByLabel("Clave de acceso infantil").fill("ClaveHijo123");
    await form.getByLabel("Edad").fill(name === "Alba" ? "10" : "13");
    if (name === "Bruno") await form.getByLabel("Avatar").selectOption("🐼");
    await form.getByRole("button", { name: "Crear perfil" }).click();
    await expect(page.getByRole("button", { name: new RegExp(name), exact: false }).last()).toBeVisible();
  }
  await page.getByRole("navigation").getByRole("button", { name: "Tareas y hábitos", exact: true }).click();
  await page.locator("summary").filter({ hasText: "Añadir una tarea desde la biblioteca" }).click();
  const libraryForm = page.getByRole("form", { name: "Crear tarea", exact: true });
  await libraryForm.getByLabel("Biblioteca de rutinas").selectOption("bed");
  await libraryForm.getByRole("button", { name: "Crear tarea" }).click();
  await expect(page.getByText("Hacer la cama", { exact: true })).toBeVisible();
  await page.getByRole("navigation").getByRole("button", { name: "Mi familia", exact: true }).click();
  await page.getByRole("button", { name: "🦊 Alba", exact: true }).click();
  const pointsForm = page.getByRole("form", { name: "Puntuar a Alba", exact: true });
  await pointsForm.getByLabel("Puntos de ajuste").fill("100");
  await pointsForm.getByLabel("Motivo del ajuste").fill("Has seguido tu plan con autonomía");
  await pointsForm.getByRole("button", { name: "Guardar ajuste" }).click();
  await expect(page.getByTestId("score-Alba")).toHaveText("100");
  await pointsForm.getByLabel("Puntos de ajuste").fill("-20");
  await pointsForm.getByLabel("Motivo del ajuste").fill("Revisamos el acuerdo de recoger después de jugar");
  await pointsForm.getByRole("button", { name: "Guardar ajuste" }).click();
  await expect(page.getByTestId("score-Alba")).toHaveText("80");
  const message = page.getByRole("form", { name: "Mensaje para Alba" });
  await message.getByLabel("Mensaje para Alba").fill("Me ha gustado cómo has vuelto a intentarlo.");
  await message.getByRole("button", { name: "Enviar mensaje" }).click();
  await expect(page.getByText("Guardado. Cada pequeño paso cuenta.")).toBeVisible();
  await page.getByRole("navigation").getByRole("button", { name: "Nuestro día", exact: true }).click();
  await page.screenshot({ path: "test-results/parent-desktop.png", fullPage: true, animations: "disabled" });

  const childContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, deviceScaleFactor: 1 });
  const child = await childContext.newPage();
  child.on("pageerror", error => errors.push(error.message));
  await child.goto("/");
  await child.getByLabel("Nombre de acceso").fill("Alba");
  await child.getByLabel("Contraseña o clave").fill("ClaveHijo123");
  await child.getByRole("button", { name: "Entrar en familia" }).click();
  await expect(child.getByRole("heading", { name: "¡Hola, Alba!" })).toBeVisible();
  await expect(child.getByTestId("score-Alba")).toHaveText("80");
  await expect(child.getByText("Bruno")).toHaveCount(0);
  await expect(child.getByText("Me ha gustado cómo has vuelto a intentarlo.")).toBeVisible();
  await expect(child.getByRole("navigation").getByRole("button", { name: "Configuración" })).toHaveCount(0);
  await child.screenshot({ path: "test-results/child-mobile.png", fullPage: true, animations: "disabled" });
  expect(await child.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await child.getByRole("navigation").getByRole("button", { name: "Mis tareas", exact: true }).click();
  const childTaskForm = child.getByRole("form", { name: "Completar Preparar la mochila para mañana", exact: true });
  await childTaskForm.locator('input[name="operation"]').evaluate((input: HTMLInputElement) => { input.value = "adjust"; });
  await childTaskForm.getByRole("button", { name: "Lo he hecho" }).click();
  await expect(child.locator("#main").getByRole("alert")).toContainText("reservada a los padres");
  await childTaskForm.locator('input[name="operation"]').evaluate((input: HTMLInputElement) => { input.value = "submit-task"; });
  await child.getByRole("form", { name: "Completar Preparar la mochila para mañana", exact: true }).getByRole("button", { name: "Lo he hecho" }).click();
  await expect(child.getByText("Por aprobar", { exact: true })).toBeVisible();
  await child.getByRole("navigation").getByRole("button", { name: "Recompensas", exact: true }).click();
  await child.getByRole("form", { name: "Solicitar Tú eliges la película", exact: true }).getByRole("button", { name: "Pedir recompensa" }).click();
  await expect(child.getByRole("button", { name: "Solicitud enviada" })).toBeVisible();
  await child.getByLabel("Mi idea", { exact: true }).fill("Visitar el planetario");
  await child.getByRole("button", { name: "Enviar mi idea" }).click();
  await expect(child.getByText("Guardado. Cada pequeño paso cuenta.")).toBeVisible();

  await page.reload();
  await page.getByRole("navigation").getByRole("button", { name: /Solicitudes/ }).click();
  const task = page.getByRole("form", { name: "Revisar Preparar la mochila para mañana", exact: true });
  await task.getByRole("button", { name: "Aprobar", exact: true }).click();
  await expect(task).toHaveCount(0);
  const reward = page.getByRole("form", { name: "Revisar Tú eliges la película", exact: true });
  await reward.getByRole("button", { name: "Aprobar", exact: true }).click();
  await expect(reward).toHaveCount(0);
  await page.getByRole("form", { name: "Entregar Tú eliges la película", exact: true }).getByRole("button", { name: "Marcar como disfrutada" }).click();
  await expect(page.getByText("Disfrutada", { exact: true })).toBeVisible();
  const idea = page.getByRole("form", { name: "Revisar Visitar el planetario", exact: true });
  await idea.getByLabel("Coste acordado").fill("80");
  await idea.getByRole("button", { name: "Aprobar y crear premio" }).click();
  await expect(idea).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  for (const name of ["Mi familia", "Tareas y hábitos", "Recompensas", "Educar en positivo", "Configuración"]) {
    await page.getByRole("navigation").getByRole("button", { name, exact: true }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  }
  const settings = page.getByRole("form", { name: "Configurar familia" });
  await settings.getByLabel("Permitir a los padres restar puntos de la barra").uncheck();
  await settings.getByRole("button", { name: "Guardar configuración" }).click();
  await expect(page.getByText("Guardado. Cada pequeño paso cuenta.")).toBeVisible();
  await page.getByRole("navigation").getByRole("button", { name: "Mi familia", exact: true }).click();
  const disabledNegative = page.getByRole("form", { name: "Puntuar a Alba", exact: true });
  await expect(disabledNegative.getByLabel("Puntos de ajuste")).toHaveAttribute("min", "1");
  await disabledNegative.getByLabel("Puntos de ajuste").evaluate((input: HTMLInputElement) => { input.min = "-100"; });
  await disabledNegative.getByLabel("Puntos de ajuste").fill("-5");
  await disabledNegative.getByLabel("Motivo del ajuste").fill("Intento con negativos desactivados");
  await disabledNegative.getByRole("button", { name: "Guardar ajuste" }).click();
  await expect(page.locator("#main").getByRole("alert")).toContainText("desactivados");
  await expect(page.getByTestId("score-Alba")).toHaveText("85");
  await child.reload();
  await expect(child.getByTestId("score-Alba")).toHaveText("85");
  await expect(child.getByText("Objetivo alcanzado", { exact: true })).toBeVisible();
  await child.getByRole("navigation").getByRole("button", { name: "Recompensas", exact: true }).click();
  await expect(child.getByRole("heading", { name: "Visitar el planetario" })).toBeVisible();
  await expect(child.locator(".balance-banner strong")).toContainText("75");
  await child.getByRole("navigation").getByRole("button", { name: "Ideas que me ayudan", exact: true }).click();
  expect(await child.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await child.getByRole("button", { name: "Cerrar sesión", exact: true }).click();
  await expect(child.getByRole("button", { name: "Entrar en familia" })).toBeVisible();
  await child.reload();
  await expect(child.getByTestId("score-Alba")).toHaveCount(0);
  expect(errors).toEqual([]);
  await childContext.close();
});
